### ISSUE TITLE
Add documentation to our API

### ISSUE THREAD

**Issue by bocops** [andregasser/bigbone#104]
All of the API functionality we offer should be documented using proper Kdoc. This will help users of this library by displaying information about any functionality they might want to use directly in their IDE.

**Comment by bocops** [comment]
I've already documented some functionality in our method classes as I touched individual files, but would like to finish the job for 2.0.0, at least regarding anything in the method directory. This is a non-breaking change, mostly copy&paste from already available documentation, so could go in at any time.

**Comment by andregasser** [comment]
Sure! Makes perfectly sense. Thanks for bringing it up.

**Comment by andregasser** [comment]
Once the KDoc is in place, we should aim for enabling the following rules in detekt:

`/config/detekt/detekt.yml`

```yaml
OutdatedDocumentation:                                                                                                
    active: true                                                                                                        
    matchTypeParameters: true                                                                                           
    matchDeclarationsOrder: true                                                                                        
    allowParamOnConstructorProperties: false                                                                            
UndocumentedPublicClass:                                                                                              
    active: true                                                                                                        
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**'] 
    searchInNestedClass: true                                                                                           
    searchInInnerClass: true                                                                                            
    searchInInnerInterface: true                                                                                        
    searchInProtectedClass: false                                                                                       
UndocumentedPublicFunction:                                                                                           
    active: true                                                                                                        
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**'] 
    searchProtectedFunction: false                                                                                      
UndocumentedPublicProperty:                                                                                           
    active: true                                                                                                        
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**'] 
    searchProtectedProperty: false                                                                                      
```
